<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'business_id' => 1,
                'name' => 'Office 365 Migration',
                'manufacturer' => null,
                'category_name' => 'General Labour',
                'barcode' => null,
                'sku' => '257892',
                'type' => 'service',
                'manage_stock' => false,
                'stock_quantity' => 0,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'description' => 'Office 365 migration service',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => '12 mini . 64GB A',
                'manufacturer' => 'Apple',
                'category_name' => 'Apple',
                'barcode' => null,
                'sku' => '353010111108116',
                'type' => 'serialized',
                'manage_stock' => true,
                'stock_quantity' => 0,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 200.00,
                'selling_price' => 0.00,
                'description' => 'iPhone 12 mini 64GB Grade A',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => '130 Black A',
                'manufacturer' => 'Nokia',
                'category_name' => 'Nokia',
                'barcode' => null,
                'sku' => '725288',
                'type' => 'standard',
                'manage_stock' => true,
                'stock_quantity' => 0,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 30.00,
                'selling_price' => 50.00,
                'description' => 'Nokia 130 Black Grade A',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => '150',
                'manufacturer' => 'Nokia',
                'category_name' => null,
                'barcode' => null,
                'sku' => '502450',
                'type' => 'standard',
                'manage_stock' => true,
                'stock_quantity' => 0,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 25.00,
                'selling_price' => 0.00,
                'description' => 'Nokia 150',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => '16GB USB Stick',
                'manufacturer' => null,
                'category_name' => null,
                'barcode' => null,
                'sku' => '1391385',
                'type' => 'standard',
                'manage_stock' => true,
                'stock_quantity' => -4,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 3.00,
                'selling_price' => 10.00,
                'description' => '16GB USB Flash Drive',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => '2D Tempered Glass',
                'manufacturer' => null,
                'category_name' => 'Accessories',
                'barcode' => null,
                'sku' => '918748',
                'type' => 'standard',
                'manage_stock' => true,
                'stock_quantity' => -1,
                'need_qty' => 0,
                'on_po_qty' => 3,
                'cost_price' => 2.00,
                'selling_price' => 15.00,
                'description' => '2D Tempered Glass Screen Protector',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => '3 pin cable',
                'manufacturer' => null,
                'category_name' => null,
                'barcode' => null,
                'sku' => '1374379',
                'type' => 'standard',
                'manage_stock' => true,
                'stock_quantity' => -1,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 4.00,
                'selling_price' => 15.00,
                'description' => '3 Pin Power Cable',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => '32GB USB Stick',
                'manufacturer' => null,
                'category_name' => null,
                'barcode' => null,
                'sku' => '1391386',
                'type' => 'standard',
                'manage_stock' => true,
                'stock_quantity' => -1,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 5.00,
                'selling_price' => 20.00,
                'description' => '32GB USB Flash Drive',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => '4G Mobile wifi pro',
                'manufacturer' => null,
                'category_name' => null,
                'barcode' => null,
                'sku' => '1303323',
                'type' => 'serialized',
                'manage_stock' => true,
                'stock_quantity' => -1,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 40.00,
                'selling_price' => 80.00,
                'description' => '4G Mobile WiFi Pro Pocket Router',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => '65W Plug',
                'manufacturer' => null,
                'category_name' => 'Accessories',
                'barcode' => null,
                'sku' => '1086893',
                'type' => 'standard',
                'manage_stock' => true,
                'stock_quantity' => -3,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 10.00,
                'selling_price' => 30.00,
                'description' => '65W Fast Charger Wall Plug',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => 'A02 Blue 32 New',
                'manufacturer' => null,
                'category_name' => null,
                'barcode' => null,
                'sku' => '535065',
                'type' => 'serialized',
                'manage_stock' => true,
                'stock_quantity' => 0,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 110.00,
                'selling_price' => 174.99,
                'description' => 'Samsung Galaxy A02 Blue 32GB Brand New',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => 'A02s Black 32 New',
                'manufacturer' => null,
                'category_name' => 'Mobile Trade-In Stock',
                'barcode' => null,
                'sku' => '553484',
                'type' => 'serialized',
                'manage_stock' => true,
                'stock_quantity' => 0,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 130.00,
                'selling_price' => 199.99,
                'description' => 'Samsung Galaxy A02s Black 32GB Brand New',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => 'A02s White 32 New',
                'manufacturer' => null,
                'category_name' => 'Mobile Trade-In Stock',
                'barcode' => null,
                'sku' => '535067',
                'type' => 'serialized',
                'manage_stock' => true,
                'stock_quantity' => 0,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 130.00,
                'selling_price' => 199.99,
                'description' => 'Samsung Galaxy A02s White 32GB Brand New',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => 'A03s 64Gb',
                'manufacturer' => 'Samsung Phones',
                'category_name' => 'Samsung Phones',
                'barcode' => null,
                'sku' => '631271',
                'type' => 'serialized',
                'manage_stock' => true,
                'stock_quantity' => 0,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'description' => 'Samsung Galaxy A03s 64GB',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => 'a10s Black',
                'manufacturer' => 'Samsung Phones',
                'category_name' => 'Samsung Phones',
                'barcode' => null,
                'sku' => '578372',
                'type' => 'serialized',
                'manage_stock' => true,
                'stock_quantity' => 0,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 120.00,
                'selling_price' => 185.00,
                'description' => 'Samsung Galaxy A10s Black',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => 'A23 lcd',
                'manufacturer' => null,
                'category_name' => null,
                'barcode' => null,
                'sku' => '1502693',
                'type' => 'standard',
                'manage_stock' => true,
                'stock_quantity' => -1,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'description' => 'Samsung A23 LCD Screen Replacement Part',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => 'A23 Screen replacement',
                'manufacturer' => null,
                'category_name' => null,
                'barcode' => null,
                'sku' => '1240016',
                'type' => 'service',
                'manage_stock' => false,
                'stock_quantity' => 0,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'description' => 'Samsung A23 Screen Repair Service',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => 'A25 Screen',
                'manufacturer' => null,
                'category_name' => null,
                'barcode' => null,
                'sku' => '1495730',
                'type' => 'standard',
                'manage_stock' => true,
                'stock_quantity' => -1,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'description' => 'Samsung A25 Screen Display Unit',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => 'A5 2017',
                'manufacturer' => null,
                'category_name' => 'Repair',
                'barcode' => null,
                'sku' => '181749',
                'type' => 'service',
                'manage_stock' => false,
                'stock_quantity' => 0,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'description' => 'Samsung A5 2017 Repair',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => 'A52s 128GB New',
                'manufacturer' => 'Samsung Phones',
                'category_name' => 'Samsung Phones',
                'barcode' => null,
                'sku' => '724988',
                'type' => 'serialized',
                'manage_stock' => true,
                'stock_quantity' => 0,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 220.00,
                'selling_price' => 330.00,
                'description' => 'Samsung Galaxy A52s 128GB Brand New',
                'is_active' => true,
            ],
            [
                'business_id' => 1,
                'name' => 'A57 5G 128GB',
                'manufacturer' => null,
                'category_name' => null,
                'barcode' => null,
                'sku' => '1664180',
                'type' => 'serialized',
                'manage_stock' => true,
                'stock_quantity' => 0,
                'need_qty' => 0,
                'on_po_qty' => 0,
                'cost_price' => 0.00,
                'selling_price' => 0.00,
                'description' => 'Oppo A57 5G 128GB',
                'is_active' => true,
            ],
        ];

        foreach ($products as $prod) {
            $prod['created_at'] = now();
            $prod['updated_at'] = now();
            DB::table('products')->updateOrInsert(
                ['sku' => $prod['sku']],
                $prod
            );
        }
    }
}
